"""Prompt pilot report on the 50 development-sitting leaves (§12.2): reports/label_pilot_n50.md.

Compares prompt versions on the same leaves: validity, tokens, projected cost, label profile, self-consistency and
agreement with v2 (full codebook). v2 is a reference, not ground truth.
Run: python -m lcbank.qa.pilot_report
"""
import json
from collections import defaultdict
from statistics import mean

from lcbank.common import config
from lcbank.common.paths import DATA_DERIVED, REPORTS
from lcbank.label.label_parts import dev_sample
from lcbank.qa.consistency import main_topic, overlap

DATASETS = {"PHY": 20, "PM": 20, "PMT": 5, "AM2": 5}
TOTAL_LEAVES = 3549
RERUN_SHARE = 0.10
QUOTA_TOKENS = 470_000  # observed input tokens before Ark's Safe Experience limit (OI-013)
PRO_GA, FLASH41, GLM53 = "deepseek-v4-pro-ga-260813", "deepseek-v4-1-flash-260910", "glm-5-3-flash-260828"
# (row label, runs, model or None for any, description)
VERSIONS = [
    ("v1", ["v1"], None, "full codebook, default sampling"),
    ("v2", ["v2"], None, "full codebook, temperature 0 (reference)"),
    ("v3 · 4.1-flash", ["v3"], FLASH41, "lean codebook (≤3 short includes), temperature 0"),
    ("v3 · pro-ga", ["v3", "v3p"], PRO_GA, "lean codebook, temperature 0"),
    ("v4 · pro-ga", ["v4"], PRO_GA, "topic names only, scoring steps (option A)"),
    ("v5 · pro-ga", ["v5"], PRO_GA, "topic names only, main + secondary, fixed weights (option B)"),
    ("v3 · glm-5-3-flash", ["v3g"], GLM53, "lean codebook, temperature 0"),
    ("v4 · glm-5-3-flash", ["v4g"], GLM53, "topic names only, scoring steps (option A)"),
    ("v5 · glm-5-3-flash", ["v5g"], GLM53, "topic names only, main + secondary, fixed weights (option B)"),
    ("v4s · 4.1-flash", ["v4s"], FLASH41, "topic names only + JSON-schema structured output (chosen for the full run)"),
]
RERUNS = [("v1", "v1", "v1r"), ("v2", "v2", "v2r"), ("v3", "v3", "v3r")]


def load():
    sample = {ds: {it["item_id"] for it in dev_sample(ds, n)} for ds, n in DATASETS.items()}
    recs = defaultdict(dict)  # run -> item -> record
    for ds in DATASETS:
        for line in open(DATA_DERIVED / "labels" / f"labels_raw_{ds}.jsonl", encoding="utf-8"):
            r = json.loads(line)
            if r["item_id"] in sample[ds]:
                recs[r["run"]][r["item_id"]] = r
    return sample, recs


def version_records(recs, runs, model):
    out = {}
    for run in runs:
        for iid, r in recs.get(run, {}).items():
            if model is None or r["model"] == model:
                out.setdefault(iid, r)
    return out


def ds_of(iid):
    return iid.split("-")[0]


def pct(x):
    return f"{100 * x:.0f}%"


def build():
    prices = config.load("prices")
    pin, pout = prices["price_in_cny_per_m"], prices["price_out_cny_per_m"]
    sample, recs = load()
    n_total = sum(len(v) for v in sample.values())
    vers = {name: version_records(recs, runs, model) for name, runs, model, _ in VERSIONS}
    vers = {k: v for k, v in vers.items() if v}
    lines = ["# Labelling prompt pilot — 50 development-sitting leaves", "",
             f"Generated by `python -m lcbank.qa.pilot_report`. Leaves: {n_total} from development sittings "
             "(PHY 2002-04: 20, PM 2014-16: 20, PMT 2012-13: 5, AM2 2023: 5), the same leaves for every version. "
             "Costs use the quoted prices (2 CNY in / 8 CNY out per million tokens) with no cache discount. "
             "v2 is the reference for agreement because it sees the full codebook; it is not ground truth.", "",
             "## Versions", "", "| Version | Prompt | Model(s) | Labelled | Valid |", "|---|---|---|---|---|"]
    for name, runs, model, desc in VERSIONS:
        if name not in vers:
            continue
        v = vers[name]
        models = sorted({r["model"] for r in v.values()})
        ok = sum(1 for r in v.values() if r["
        lines.append(f"| {name} | {desc} | {', '.join(models) or '—'} | {len(v)}/{n_total} | {ok}/{len(v) if v else 0} |")

    lines += ["", "## Tokens and projected cost", "",
              "| Version | Input tokens / leaf | Output tokens / leaf | CNY / leaf | Full run tokens (M) | Full run CNY | Leaves per free quota |",
              "|---|---|---|---|---|---|---|"]
    for name in vers:
        v = [r for r in vers[name].values() if r["
        if not v:
            continue
        tin, tout = mean(r["tokens_in"] for r in v), mean(r["tokens_out"] for r in v)
        per = tin / 1e6 * pin + tout / 1e6 * pout
        full = TOTAL_LEAVES * (1 + RERUN_SHARE)
        lines.append(f"| {name} | {tin:,.0f} | {tout:,.0f} | {per:.4f} | {full * (tin + tout) / 1e6:.1f} | "
                     f"{full * per:.1f} | {QUOTA_TOKENS / tin:,.0f} |")

    lines += ["", "## Label profile", "",
              "| Version | Topics per leaf | UNCLEAR share of weight | Based on marking scheme | needs_diagram | Mean confidence |",
              "|---|---|---|---|---|---|"]
    for name in vers:
        v = [r for r in vers[name].values() if r["
        if not v:
            continue
        lines.append(
            f"| {name} | {mean(len(r['weights']) for r in v):.2f} | "
            f"{mean(sum(w['weight'] for w in r['weights'] if w['topic_id'] == 'UNCLEAR') / 100 for r in v):.1%} | "
            f"{pct(mean(r['response'].get('basis') == 'marking_scheme' for r in v))} | "
            f"{pct(mean(bool(r['response'].get('needs_diagram')) for r in v))} | "
            f"{mean(float(r['response'].get('confidence', 0)) for r in v):.2f} |")

    lines += ["", "## Self-consistency (same leaves labelled twice, §13 A2 target ≥ 0.85)", "",
              "| Version | Pairs | Same model in both runs | Weight overlap | Main-topic agreement |", "|---|---|---|---|---|"]
    for name, a, b in RERUNS:
        pa, pb = recs.get(a, {}), recs.get(b, {})
        common = [i for i in pa if i in pb and pa[i]["
        for label, subset in (("all pairs", common), ("same model only", [i for i in common if pa[i]["model"] == pb[i]["model"]])):
            if subset:
                lines.append(f"| {name} ({label}) | {len(subset)} | {sum(pa[i]['model'] == pb[i]['model'] for i in subset)} | "
                             f"{mean(overlap(pa[i]['weights'], pb[i]['weights']) for i in subset):.2f} | "
                             f"{mean(main_topic(pa[i]['weights']) == main_topic(pb[i]['weights']) for i in subset):.2f} |")
    lines.append("")
    lines.append("v4 and v5 were run once (no rerun); at temperature 0 on one model, reruns of v2/v3 were close to deterministic.")

    lines += ["", "## Agreement with v2 (full codebook)", "",
              "| Version | Leaves | Weight overlap | Main-topic agreement | PHY | PM | PMT | AM2 |", "|---|---|---|---|---|---|---|---|"]
    ref = vers["v2"]
    for name in vers:
        if name == "v2":
            continue
        v = vers[name]
        common = [i for i in v if i in ref and v[i]["
        if not common:
            continue
        cells = []
        for ds in DATASETS:
            sub = [i for i in common if ds_of(i) == ds]
            cells.append(f"{mean(main_topic(v[i]['weights']) == main_topic(ref[i]['weights']) for i in sub):.2f} (n={len(sub)})"
                         if sub else "—")
        lines.append(f"| {name} | {len(common)} | {mean(overlap(v[i]['weights'], ref[i]['weights']) for i in common):.2f} | "
                     f"{mean(main_topic(v[i]['weights']) == main_topic(ref[i]['weights']) for i in common):.2f} | " + " | ".join(cells) + " |")

    lines += ["", "## Head-to-head on the same model (main-topic agreement / weight overlap)", "",
              "| Model | Pair | Leaves | Main-topic agreement | Weight overlap |", "|---|---|---|---|---|"]
    for model_label in ("pro-ga", "glm-5-3-flash"):
        for a, b in (("v3", "v4"), ("v3", "v5"), ("v4", "v5")):
            ka, kb = f"{a} · {model_label}", f"{b} · {model_label}"
            if ka in vers and kb in vers:
                common = [i for i in vers[ka] if i in vers[kb] and vers[ka][i]["
                if common:
                    lines.append(f"| {model_label} | {a} vs {b} | {len(common)} | "
                                 f"{mean(main_topic(vers[ka][i]['weights']) == main_topic(vers[kb][i]['weights']) for i in common):.2f} | "
                                 f"{mean(overlap(vers[ka][i]['weights'], vers[kb][i]['weights']) for i in common):.2f} |")
    lines += ["", "## Where v4 or v5 (glm-5-3-flash) pick a different main topic from v2", "",
              "| Leaf | v2 | v3 | v4 | v5 |", "|---|---|---|---|---|"]
    shown = 0
    for iid in sorted(ref):
        keys = {"v2": "v2", "v3": "v3 · glm-5-3-flash", "v4": "v4 · glm-5-3-flash", "v5": "v5 · glm-5-3-flash"}
        mains = {k: (main_topic(vers[kk][iid]["weights"]) if kk in vers and iid in vers[kk] and vers[kk][iid]["
                     else "—") for k, kk in keys.items()}
        if mains["v2"] != "—" and (mains["v4"] not in (mains["v2"], "—") or mains["v5"] not in (mains["v2"], "—")):
            lines.append(f"| {iid} | {mains['v2']} | {mains['v3']} | {mains['v4']} | {mains['v5']} |")
            shown += 1
    if not shown:
        lines.append("| none | | | | |")
    lines += ["", "## Notes", "",
              "- v1 used flash-ga-260731 (its rerun v1r partly pro-260425), v2 used pro-260425; their free quotas are used up. "
              "pro-ga-260813's quota ran out part-way (v3 20, v4 49, v5 40 leaves), so v3, v4 and v5 were rerun in full on "
              "glm-5-3-flash-260828 for a same-model comparison.",
              "- v5 does not follow the binding step design of Appendix B.1 (weights are fixed at 100 / 70-30 / 60-20-20); "
              "it is included only because it was compared for reference.",
              "- Neither usable model reads images; all versions are text-only (question text, stem, marking-scheme excerpt)."]
    (REPORTS / "label_pilot_n50.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return vers


if __name__ == "__main__":
    build()
    print((REPORTS / "label_pilot_n50.md").read_text()[:200])
