"""Aggregate every simulator shard and write reports/simulator_controls.md (§15.7).

The simulator runs the whole engine on synthetic sittings whose true structure is known:
delta = 0 means nothing is predictable, so a method that reports a signal there is a false positive;
delta = 1.5 means a real signal the engine must find. The controls G0 and G1 gate the real run.
Run: python -m lcbank.analysis.sim_report
"""
import json

from lcbank.analysis.sim import summarise
from lcbank.common.paths import ANALYSIS, REPORTS


def load_runs():
    return [json.loads(l) for p in sorted((ANALYSIS / "sim").glob("simulator_runs*.jsonl"))
            for l in open(p, encoding="utf-8")]


def write_report(summary, checks, runs):
    lines = ["# Simulator controls (§15.7)", "",
             f"Generated by `python -m lcbank.analysis.sim_report` over {len(runs)} runs "
             "(99 permutations each, D-029). Synthetic sittings with a known structure: `delta` is how much "
             "genuine year-to-year signal was built in, so `delta = 0` is a world where nothing is predictable "
             "and every rejection there is a false positive.", "",
             "| Scenario | Runs | H2 reject | H3 reject | H2 CI covers 0 | mean H2 | mean H3 slope |",
             "|---|---|---|---|---|---|---|"]
    for key, s in summary.items():
        lines.append(f"| {key} | {s['runs']} | {s['H2_reject_rate']:.3f} | {s['H3_reject_rate']:.3f} | "
                     f"{s['H2_ci_covers_zero']:.3f} | {s['mean_h2']:.4f} | {s['mean_h3_beta']:.4f} |")
    lines += ["", "## Control checks", "",
              "| Check | Result |", "|---|---|"]
    for name, ok in checks.items():
        lines.append(f"| {name} | {'PASS' if ok else '**FAIL**'} |")
    failed = [k for k, ok in checks.items() if not ok]
    lines += ["", ("All controls pass, so the engine may be run on the real data (§15.8)." if not failed else
                   f"**{len(failed)} control(s) failed — the real run stays blocked (§15.7).** Failing: {failed}")]
    (REPORTS / "simulator_controls.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return failed


if __name__ == "__main__":
    runs = load_runs()
    summary, checks = summarise(runs)
    failed = write_report(summary, checks, runs)
    print(json.dumps({"runs": len(runs), "scenarios": {k: v["runs"] for k, v in summary.items()},
                      "checks": checks, "failed": failed}, indent=1))
    raise SystemExit(1 if failed else 0)
