"""Phase 7: topic x sitting tables and descriptive per-topic history (§14).

offered_marks[s,k] = sum over leaves of marks x weight_k / 100 (all offered parts, choices included)
share[s,k]         = offered_marks / the paper's max score from the rules tree
appears[s,k]       = share >= 1.5% (sensitivity columns at 0.75% and 3%)
These are historical facts only (R1): no ranking, probability or "due" statement anywhere.
Run: python -m lcbank.analysis.tables
"""
import csv
import json

import numpy as np

from lcbank.analysis.data import load_dataset
from lcbank.common.paths import DATA_DERIVED, REPORTS

STATS = DATA_DERIVED / "stats"
THRESHOLDS = {"appears": 0.015, "appears_0p75": 0.0075, "appears_3p0": 0.03}
# In the bank and described here, but never analysed: AM2 has four sittings, PMT is the 2012-2013
# transitional variant. Both carry analysis_excluded, so the analysis engine cannot read them.
DESCRIPTIVE_ONLY = ("PMT", "AM2")


def topic_sitting_rows(data, sitting_type="main"):
    rows = []
    for i, s in enumerate(data.sittings):
        for k, topic in enumerate(data.topics):
            share = float(data.share[i, k])
            rows.append({"dataset": data.name, "year": s.year, "sitting_type": sitting_type, "topic_id": topic,
                         "offered_marks": round(share * s.max_score, 3), "max_score": s.max_score,
                         "share": round(share, 6),
                         **{name: int(share >= thr) for name, thr in THRESHOLDS.items()}})
    return rows


def topic_history_rows(data):
    rows = []
    n = len(data.sittings)
    years = np.array(data.years)
    for k, topic in enumerate(data.topics):
        appears = data.appears[:, k]
        share = data.share[:, k]
        idx = np.flatnonzero(appears)
        gaps = np.diff(idx) if len(idx) > 1 else np.array([])
        longest = int(max(gaps) - 1) if len(gaps) else (0 if len(idx) else n)
        rows.append({"dataset": data.name, "topic_id": topic, "sittings_present": n,
                     "appearance_count": int(appears.sum()),
                     "appearance_rate": round(float(appears.mean()), 4),
                     "mean_share": round(float(share.mean()), 6), "sd_share": round(float(share.std(ddof=0)), 6),
                     "longest_gap_sittings": longest,
                     "first_year": int(years[idx[0]]) if len(idx) else None,
                     "last_year": int(years[idx[-1]]) if len(idx) else None})
    return rows


def check_totals(data, rows):
    """Offered marks per sitting must equal the marks-weighted topic total of its leaves (UNCLEAR excluded)."""
    problems = []
    for i, s in enumerate(data.sittings):
        expected = 0.0
        for it in s.items:
            for w in it["topics"] or []:
                if w["topic_id"] in set(data.topics):
                    expected += it["marks"] * w["weight"] / 100.0
        got = sum(r["offered_marks"] for r in rows if r["year"] == s.year)
        if abs(got - expected) > 0.05:
            problems.append((s.year, round(got, 3), round(expected, 3)))
    return problems


def build(datasets=("PHY", "PM", "PMT", "AM2")):
    STATS.mkdir(parents=True, exist_ok=True)
    report = ["# Topic × sitting tables (Phase 7)", "",
              "Generated by `python -m lcbank.analysis.tables`. Historical facts only (R1): appearance counts and "
              "mark shares of past sittings. `appears` uses the 1.5% threshold; the 0.75% and 3% columns are the "
              "sensitivity thresholds.", "",
              "PMT and AM2 are described here but never analysed (`analysis_excluded`): PMT is the 2012-2013 "
              "transitional variant and AM2 has only four sittings.", "",
              "| Dataset | Sittings | Topics | Rows | Mean topics appearing per sitting | Totals check |",
              "|---|---|---|---|---|---|"]
    for name in datasets:
        try:
            data = load_dataset(name, labelled=True, include_excluded=name in DESCRIPTIVE_ONLY)
        except FileNotFoundError:
            report.append(f"| {name} | — | — | — | — | labels not available yet |")
            continue
        if not data.sittings:
            report.append(f"| {name} | 0 | {len(data.topics)} | 0 | — | no sitting to describe |")
            continue
        rows = topic_sitting_rows(data)
        problems = check_totals(data, rows)
        with open(STATS / f"topic_sitting_{name}.csv", "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(rows[0]))
            w.writeheader()
            w.writerows(rows)
        hist = topic_history_rows(data)
        with open(STATS / f"topic_history_{name}.csv", "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=list(hist[0]))
            w.writeheader()
            w.writerows(hist)
        report.append(f"| {name} | {len(data.sittings)} | {len(data.topics)} | {len(rows)} | "
                      f"{data.appears.sum(axis=1).mean():.1f} | {'OK' if not problems else problems[:3]} |")
    (REPORTS / "topic_tables.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    return report


if __name__ == "__main__":
    print("\n".join(build()))
