"""Phase 2.5: reports/extraction_quality.md — pages per extraction method and usable-text share per dataset."""
import csv
import json
from collections import defaultdict

from lcbank.common.paths import MANIFEST, REPORTS, TEXT


def run():
    with open(MANIFEST, newline="", encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if r["sha256"]]
    stats = defaultdict(lambda: defaultdict(int))
    flagged = []
    missing = []
    for r in rows:
        summary_path = TEXT / r["doc_id"] / "pages.json"
        if not summary_path.exists():
            if r["title_check"] == "pass":
                missing.append(r["doc_id"])
            continue
        key = (r["dataset"], r["doc_type"])
        for p in json.loads(summary_path.read_text())["pages"]:
            s = stats[key]
            s["pages"] += 1
            s[p["extraction_method"]] += 1
            s["blank"] += p["blank"]
            usable = p["extraction_method"] in ("text", "ocr", "vision") and not p["blank"]
            s["usable"] += usable
            s["non_blank"] += not p["blank"]
            if p["extraction_method"] == "needs_ocr":
                flagged.append(f"{r['doc_id']} p{p['page']} ({p['chars']} chars, image covers {p.get('image_coverage', 0):.0%})")
    methods = ["text", "ocr", "vision", "needs_ocr"]
    lines = ["# Extraction quality (Phase 2)", "",
             "Generated by `python -m lcbank.extract.quality_report`. A page is *scanned* (`needs_ocr`) if it has "
             "fewer than 150 extractable characters, is not blank, and an image covers more than 30% of it (§9.3, refined in. "
             "Usable text share = pages with usable text ÷ non-blank pages.", "",
             "| Dataset | Doc type | Pages | " + " | ".join(methods) + " | Blank | Usable text share |",
             "|---|---|---|" + "---|" * len(methods) + "---|---|"]
    for (ds, dt), s in sorted(stats.items()):
        share = s["usable"] / s["non_blank"] if s["non_blank"] else float("nan")
        lines.append(f"| {ds} | {dt} | {s['pages']} | " + " | ".join(str(s[m]) for m in methods)
                     + f" | {s['blank']} | {share:.1%} |")
    lines += ["", f"## Pages still needing OCR or vision transcription ({len(flagged)})", ""]
    lines += [f"- {x}" for x in flagged[:200]] or ["- none"]
    if len(flagged) > 200:
        lines.append(f"- … {len(flagged) - 200} more")
    lines += ["", f"## Title-checked documents not yet extracted ({len(missing)})", ""]
    lines += [f"- {x}" for x in missing] or ["- none"]
    (REPORTS / "extraction_quality.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return stats, flagged, missing


if __name__ == "__main__":
    stats, flagged, missing = run()
    print(f"datasets×types: {len(stats)}; needs_ocr pages: {len(flagged)}; not extracted: {len(missing)}")
